# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crapshoot}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bryce Kerley"]
  s.date = %q{2010-12-28}
  s.description = %q{Crapshoot is a dice-rolling gem that parses complicated notation for most of your pen-and-paper gaming needs.}
  s.email = %q{bkerley@brycekerley.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "crapshoot.gemspec",
    "lib/crapshoot.rb",
    "lib/crapshoot/evaluator.rb",
    "lib/crapshoot/parser/scan.rb",
    "lib/crapshoot/parser/scan.rl",
    "lib/crapshoot/postfixer.rb",
    "lib/crapshoot/scanner.rb",
    "lib/crapshoot/tokens/arithmetic.rb",
    "lib/crapshoot/tokens/base.rb",
    "lib/crapshoot/tokens/constant.rb",
    "lib/crapshoot/tokens/series.rb",
    "test/helper.rb",
    "test/test_crapshoot.rb",
    "test/test_evaluator.rb",
    "test/test_postfixer.rb",
    "test/test_scanner.rb"
  ]
  s.homepage = %q{http://github.com/bkerley/crapshoot}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The alpha and omega of rolling dice}
  s.test_files = [
    "test/helper.rb",
    "test/test_crapshoot.rb",
    "test/test_evaluator.rb",
    "test/test_postfixer.rb",
    "test/test_scanner.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<guard-test>, ["~> 0.1.4"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<guard-test>, ["~> 0.1.4"])
      s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_dependency(%q<bundler>, ["~> 1.0.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<guard-test>, ["~> 0.1.4"])
    s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
    s.add_dependency(%q<activesupport>, ["~> 3.0"])
    s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
    s.add_dependency(%q<bundler>, ["~> 1.0.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

